{% set version="1.6" %}

package:
  name: minnow
  version: {{ version }}

source:
  url: https://github.com/COMBINE-lab/minnow/archive/{{ version  }}.tar.gz
  sha256: 5727e45a985b734743305a3d2a4a56b60063c70d1f2fde905bffee72dce97284

build:
  number: 0

requirements:
  build:
    - autoconf
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - icu 
    - zlib
    - bzip2
    - unzip
  run:
    - zlib
    - bzip2

test:
  commands:
    - minnow --help

about:
  home: https://github.com/COMBINE-lab/minnow
  license: GPLv3
  summary: A principled framework for rapid simulation of dscRNA-seq data at the read level
