{% set name = "gffcompare" %}
{% set version = "0.11.10" %}
{% set sha256hash = "020db67e839e1f102d54c6ba4c8b14c245ae18e72333c3ad155b6b167d0f319c" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  skip: False

source:
  - url: https://github.com/gpertea/gffcompare/archive/v{{ version }}.tar.gz
    sha256: {{ sha256hash }}
    folder: gffcompare
    patches:
      - Makefile.patch
  - url: https://github.com/gpertea/gclib/archive/v{{ version }}.tar.gz
    sha256: e02e89336d4be40aa8b4ee0623f616792c45821ade41aae86a16d09759c6640c
    folder: gclib

requirements:
  build:
    - {{ compiler('cxx') }}

test:
  commands:
    - gffcompare -v

about:
  home: "https://ccb.jhu.edu/software/stringtie/gffcompare.shtml"
  license: 'Artistic License 2.0'
  summary: 'GffCompare by Geo Pertea'

extra:
  identifiers:
    - biotools:gffcompare
