{% set version = "1.1.0" %}

package:
  name: revbayes
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/revbayes/revbayes/archive/v{{ version }}.tar.gz
  sha256: bb01f50bfb20c99cdf0d0d9ef07bafca37673ae97c1cd89823e774185c3db028

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=2.6
  host:
    - boost-cpp >=1.60
    - openmpi
  run:
    - boost-cpp >=1.60
    - openmpi

test:
  commands:
    - rb -v
    - rb -h
    - rb-mpi -v
    - rb-mpi -h

about:
  home: https://revbayes.github.io/
  license: GPLv3
  license_file: LICENSE
  summary: Bayesian phylogenetic inference using probabilistic graphical models and an interactive language.

extra:
  container:
    # openmpi needs ssh/rsh
    extended-base: true
