package:
  name: preseq
  version: 3.0

source:
  url: https://github.com/smithlabcode/preseq/releases/download/v3.0/preseq-3.0.tar.gz
  sha256: 5f14c392abae79909c2e5b7eeb2e77a6681957090fea66979094c6d1a25326b5
  patches: Makefile.patch

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - zlib
    - gsl
    - openblas
  run:
    - zlib
    - gsl
    - openblas

test:
  commands:
    - preseq
    - bam2mr

about:
  home: https://github.com/smithlabcode/preseq
  license: GNU GENERAL PUBLIC LICENSE
  summary: 'Software for predicting library complexity and genome coverage in high-throughput sequencing'
