package:
  name: preseq
  version: 3.0.1

source:
  url: https://github.com/smithlabcode/preseq/releases/download/v3.0.1/preseq-3.0.1.tar.gz
  sha256: 9bdc8c3265f04322c559cf9a8dc1a6668055dc666fbaf2b173ded8d35110d117
  patches: Makefile.patch

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - zlib
    - gsl
    - openblas
  run:
    - zlib
    - gsl
    - openblas

test:
  commands:
    - preseq
    - bam2mr

about:
  home: https://github.com/smithlabcode/preseq
  license: GNU GENERAL PUBLIC LICENSE
  summary: 'Software for predicting library complexity and genome coverage in high-throughput sequencing'
