package:
  name: preseq
  version: 3.0.2

source:
  url: https://github.com/smithlabcode/preseq/releases/download/v3.0.2/preseq-3.0.2.tar.gz
  sha256: 727b190d2d6018ae931b151d31ff8cd3593b36e58b0a9fe54335fa747fd56b21
  patches: Makefile.patch

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - zlib
    - gsl
    - openblas
  run:
    - zlib
    - gsl
    - openblas

test:
  commands:
    - preseq
    - bam2mr

about:
  home: https://github.com/smithlabcode/preseq
  license: GNU GENERAL PUBLIC LICENSE
  summary: 'Software for predicting library complexity and genome coverage in high-throughput sequencing'
